# Generated by Django 3.2.16 on 2024-04-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(
                    blank=True, verbose_name='auto_now_add')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(
                    blank=True, verbose_name='auto_now_add')),
                ('name', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(
                    blank=True, verbose_name='auto_now_add')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('text', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True)),
                ('author', models.ForeignKey(
                    blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('location', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
